routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('users/subscriptions','AdminController@users_subscriptions_index')->name('users.subscriptions_index');

        Route::post('users/subscription_payments','AdminController@users_subscription_payments_save')->name('users.subscriptions_payments');

        Route::get('users/subscriptions_payments/delete','AdminController@users_subscription_payments_delete')->name('users.subscriptions_payments_delete');

        //subscriptions
        Route::get('subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'AdminController@subscriptions_status')->name('subscriptions.status');

        //Subscription Payments
        Route::get('subscription_payments/index','AdminController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','AdminController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenue/dashboard','AdminController@revenue_dashboard')->name('revenue.dashboard');

        //meetings crud
        Route::get('meetings', 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/create', 'AdminController@meetings_create')->name('meetings.create');

        Route::get('meetings/edit', 'AdminController@meetings_edit')->name('meetings.edit');

        Route::post('meetings/save', 'AdminController@meetings_save')->name('meetings.save');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');

        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');

        Route::get('meetings/status', 'AdminController@meetings_status')->name('meetings.status');

        // settings

        Route::get('settings-control', 'AdminController@settings_control')->name('control');

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 
        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('/static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('/static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('/static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('/static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('/static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('/static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('/static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        // SUPPORT CONTACTS

        Route::get('support_contacts' , 'AdminController@support_contacts_index')->name('support_contacts.index');

        Route::get('support_contacts/view', 'AdminController@support_contacts_view')->name('support_contacts.view');


        Route::get('meeting_records', 'AdminController@meeting_records_index')->name('meeting_records.index');

        Route::get('meeting_records/view', 'AdminController@meeting_records_view')->name('meeting_records.view');

        Route::get('meeting_records/delete', 'AdminController@meeting_records_delete')->name('meeting_records.delete');

    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

app/Subscription.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subscription extends Model
{ 
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'description', 'plan', 'amount', 'no_of_minutes', 'no_of_users'];

    protected $hidden = ['id', 'unique_id'];

    protected $appends = ['subscription_id', 'subscription_unique_id', 'plan_formatted', 'amount_formatted', 'currency', 'no_of_users_formatted', 'no_of_minutes_formatted'];

    public function getSubscriptionIdAttribute() {

        return $this->id;
    }

    public function getSubscriptionUniqueIdAttribute() {

        return $this->unique_id;
    }

    public function getPlanFormattedAttribute() {

        return formatted_plan($this->plan, $this->plan_type);
    }

    public function getAmountFormattedAttribute() {

        return formatted_amount($this->amount);
    }

    public function getNoOfUsersFormattedAttribute() {

        return no_of_users_formatted($this->no_of_users);
    }

    public function getNoOfMinutesFormattedAttribute() {

        return no_of_minutes_formatted($this->no_of_minutes);
    }

    public function getCurrencyAttribute() {

        return \Setting::get('currency' , '$');
    }

    public function subscriptionPayments() {

    	return $this->hasMany(SubscriptionPayment::class,'subscription_id');
    }

    /**
     * Scope a query to only include approved records.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeApproved($query) {

        return $query->where('subscriptions.status', APPROVED);
    
    }

    /**
     * Scope a query to only include approved records.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeCurrentPlan($query, $user_id) {

        return $query->leftJoin('subscription_payments', 'subscription_payments.subscription_id', '=', 'subscriptions.id')
            ->where('subscription_payments.user_id', $user_id)
            ->where('subscription_payments.is_current_subscription', YES)
            ->select('subscriptions.id as subscription_id', 'subscriptions.*');
    
    }

    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['unique_id'] = "SI-"."-".uniqid();
        });

        static::created(function($model) {

            $model->attributes['unique_id'] = "SI-"."-".$model->attributes['id']."-".uniqid();

            $model->save();
        
        });

        static::deleting(function ($model){

           $model->subscriptionPayments()->delete();

        });
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Setting, DB;
use App\Notifications\ResetPassword as ResetPasswordNotification;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $appends = [
        'user_id', 'user_unique_id'
    ];

    public function getUserIdAttribute() {

        return $this->id;
    }

    public function getUserUniqueIdAttribute() {

        return $this->unique_id;
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the UserCard record associated with the user.
     */
    public function userCards() {
        
        return $this->hasMany(UserCard::class, 'user_id');
    }

    public function getSubscribedusers()
    {
        return $this->hasMany(SubscriptionPayment::class, 'user_id', 'id');
    }

    public function getMeetingUsers() {

        return $this->hasMany(MeetingUser::class, 'user_id');
    }

    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

            $model->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            if (Setting::get('is_account_email_verification') == YES && envfile('MAIL_USERNAME') && envfile('MAIL_PASSWORD')) { 

                if($model->attributes['login_by'] == 'manual') {

                    $model->generateEmailCode();

                }

            }

            $model->attributes['payment_mode'] = COD;

            $model->attributes['username'] = routefreestring($model->attributes['name']).rand(1,999999);

            $model->attributes['unique_id'] = uniqid();

            $model->attributes['token'] = \Helper::generate_token();

            $model->attributes['token_expiry'] = \Helper::generate_token_expiry();

            $model->attributes['status'] = USER_APPROVED;

            if(in_array($model->attributes['login_by'], ['facebook', 'google', 'apple', 'linkedin', 'instagram'] )) {
                
                $model->attributes['password'] = \Hash::make($model->attributes['social_unique_id']);
            }

        });

        static::created(function($model) {

            $model->attributes['email_notification_status'] = $model->attributes['push_notification_status'] = YES;

            $model->attributes['unique_id'] = "UID"."-".$model->attributes['id']."-".uniqid();

            $model->save();
        
        });

        static::updating(function($model) {

            $model->attributes['username'] = routefreestring($model->attributes['name']).rand(1,999999);

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

        });

        static::deleting(function ($model){

            \Helper::delete_file($model->picture , PROFILE_PATH_USER);

            $model->userCards()->delete();

            $model->Meeting()->delete();

            $model->SubscriptionPayment()->delete();

            $model->SupportContact()->delete();

            $model->meetingUsers()->delete();

        });

    }


    /**
     * Get the meetings record associated with the user.
     */
    public function Meeting() {
        
        return $this->hasMany(Meeting::class, 'user_id');
    }

    public function SubscriptionPayment() {
        
        return $this->hasMany(SubscriptionPayment::class, 'user_id');
    }

    public function SupportContact() {
        
        return $this->hasMany(SupportContact::class, 'user_id');
    }

    public function meetingUsers() {

        return $this->hasMany(MeetingUser::class,'user_id');
    }

    /**
     * Generates Token and Token Expiry
     * 
     * @return bool returns true if successful. false on failure.
     */

    protected function generateEmailCode() {

        $this->attributes['verification_code'] = \Helper::generate_email_code();

        $this->attributes['verification_code_expiry'] = \Helper::generate_email_expiry();

        // Check Email verification controls and email configurations

        if(Setting::get('is_account_email_verification') == YES && Setting::get('is_email_notification') == YES && Setting::get('is_email_configured') == YES) {

            if($model->attributes['login_by'] != 'manual') {

                $this->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            } else {

                $this->attributes['is_verified'] = USER_EMAIL_NOT_VERIFIED;
            }

        } else { 

            $this->attributes['is_verified'] = USER_EMAIL_VERIFIED;
        }

        return true;
    
    }

}

resources/views/admin/users/subscriptions/index.blade.php
@extends('layouts.admin')

@section('content-header', tr('users'))

@section('bread-crumb')

    <li class="breadcrumb-item">
    	<a href="{{ route('admin.users.index') }}">{{tr('users')}}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{tr('subscription_history')}}</span>
    </li>
           
@endsection 

@section('content')

<div class="row">

    <div class="col-12">

        <div class="card">

            <div class="card-body">


                <div class="border-bottom pb-3">

                    <h5 class="text-uppercase">{{tr('subscription_history')}}

                        - <a href="{{route('admin.users.view' , ['user_id' => $user_details->id ?? 0])}}">{{$user_details->name}}</a>
                  
                    </h5>

                </div>

                <div class="pt-3 pb-3">
                    <table id="basic-datatable" class="table dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th>{{tr('s_no')}}</th>
                                <th>{{tr('payment_id')}}</th>
                                <th>{{tr('subscription')}}</th>
                                <th>{{tr('plan')}}</th>
                                <th>{{tr('amount')}}</th> 
                                <th>{{tr('expiry_date')}}</th>        
                                <th>{{tr('action')}}</th>
                            </tr>
                        </thead>

                        <tbody>

                            @foreach($subscripton_payment_history as $i => $payment_details)
                                  
                                <tr>
                                    <td>{{$i+$subscripton_payment_history->firstItem()}}</td>

                                    <td>
                                        <a href="{{route('admin.subscription_payments.view' , ['subscription_payment_id' => $payment_details->id ?? 0])}}">{{$payment_details->payment_id}}</a>
                                    </td>

                                    <td>
                                        <a href="{{route('admin.subscriptions.view' , ['subscription_id' => $payment_details->subscriptionDetails->id ?? 0])}}"> {{ $payment_details->subscriptionDetails->title ?? '-' }}
                                        </a>
                                    </td>

                                    <td> {{$payment_details->plan_formatted}} </td>

                                    <td>{{$payment_details->subscription_amount_formatted}}</td>

                                    <td class="text-danger">{{common_date($payment_details->expiry_date,Auth::guard('admin')->user()->timezone)}}</td>

                                    <td>     
                                        @if(Setting::get('is_demo_control_enabled') == NO)
                                      
                                            <a class="btn btn-danger" href="{{route('admin.users.subscriptions_payments_delete', ['subscription_payment_id' => $payment_details->id])}}" 
                                            onclick="return confirm(&quot;{{tr('subscription_history_delete_confirmation')}}&quot;);">
                                                {{tr('delete')}}
                                            </a>
                                        @endif

                                    </td>

                                </tr>

                            @endforeach

                        </tbody>
                       
                    </table>

                    <div class="float-right">{{ $subscripton_payment_history->links() }}</div>

                </div>
                
            </div>
            
        </div>
        
    </div>
   
</div>


<div class="row">

	@foreach($subscriptions as $subscription_details)

		<div class="col-md-2 sub_box_css" >   

			<div class="card">

			   <div class="card-body">

			      	<h3 class="text-center text-uppercase">{{$subscription_details->title}}</h3>

                    <div class="media mt-1 border-top pt-3">

                        <div class="media-body">

                            <h6 class="mt-1 mb-0 font-size-15">{{tr('no_of_users')}}</h6>
                            <h6 class="text-muted font-weight-normal mt-1 mb-3">{{$subscription_details->no_of_users_formatted}}</h6>

                            <h6 class="mt-1 mb-0 font-size-15">{{tr('no_of_minutes')}}</h6>
                            <h6 class="text-muted font-weight-normal mt-1 mb-3">{{$subscription_details->no_of_minutes_formatted}}</h6>

                            <h6 class="mt-1 mb-0 font-size-15">{{tr('plan')}}</h6>
                            <h6 class="text-muted font-weight-normal mt-1 mb-3">{{$subscription_details->plan_formatted}}</h6>

                            <h6 class="mt-1 mb-0 font-size-15">{{tr('amount')}}</h6>

                            <h6 class="text-muted font-weight-normal mt-1 mb-3">{{$subscription_details->amount_formatted}}</h6>

                        </div>

                    </div>

					<form action="{{route('admin.users.subscriptions_payments')}}" method="POST">
						@csrf
						<input type="hidden" name="subscription_id" value="{{$subscription_details->id}}">

						<input type="hidden" name="user_id" value="{{Request::get('user_id')}}">

						<button class="btn btn-danger btn-block" type="submit" onclick="return confirm('{{tr('do_you_want_to_subscribe_this_plan')}}')">{{tr('subscribe')}}</button>

					</form>

			   </div>

			</div>
	           
	    </div>

    @endforeach

</div>

@endsection