routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('users/subscriptions','AdminController@users_subscriptions_index')->name('users.subscriptions_index');

        Route::post('users/subscription_payments','AdminController@users_subscription_payments_save')->name('users.subscriptions_payments');

        Route::get('users/subscriptions_payments/delete','AdminController@users_subscription_payments_delete')->name('users.subscriptions_payments_delete');

        //subscriptions
        Route::get('subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'AdminController@subscriptions_status')->name('subscriptions.status');

        //Subscription Payments
        Route::get('subscription_payments/index','AdminController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','AdminController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenue/dashboard','AdminController@revenue_dashboard')->name('revenue.dashboard');

        //meetings crud
        Route::get('meetings', 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/create', 'AdminController@meetings_create')->name('meetings.create');

        Route::get('meetings/edit', 'AdminController@meetings_edit')->name('meetings.edit');

        Route::post('meetings/save', 'AdminController@meetings_save')->name('meetings.save');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');

        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');

        Route::get('meetings/status', 'AdminController@meetings_status')->name('meetings.status');

        // settings

        Route::get('settings-control', 'AdminController@settings_control')->name('control');

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 
        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('/static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('/static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('/static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('/static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('/static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('/static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('/static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        // SUPPORT CONTACTS

        Route::get('support_contacts' , 'AdminController@support_contacts_index')->name('support_contacts.index');

        Route::get('support_contacts/view', 'AdminController@support_contacts_view')->name('support_contacts.view');


        Route::get('meeting_records', 'AdminController@meeting_records_index')->name('meeting_records.index');

        Route::get('meeting_records/view', 'AdminController@meeting_records_view')->name('meeting_records.view');

        Route::get('meeting_records/delete', 'AdminController@meeting_records_delete')->name('meeting_records.delete');

    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

app/StaticPage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StaticPage extends Model
{
    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeCommonResponse($query) {

        return $query->select('static_pages.*', 'static_pages.id as static_page_id', 'static_pages.unique_id as static_page_unique_id');
    
    }
}

resources/views/admin/static_pages/_form.blade.php
<div class="col-lg-12 grid-margin stretch-card">

    <div class="row flex-grow">

        <div class="col-12 grid-margin">

            <div class="card">

                <div class="card-body">

                    <div class="border-bottom pb-3">

                        <h5 class="text-uppercase">@yield('title')

                            <a class="btn btn-outline-primary float-right" href="{{route('admin.static_pages.index')}}">
                                <i class="fa fa-plus"></i> {{tr('view_static_pages')}}
                            </a>
                      
                        </h5>

                    </div>

                    @if(Setting::get('is_demo_control_enabled') == NO )

                        <form class="forms-sample" action="{{ route('admin.static_pages.save') }}" method="POST" enctype="multipart/form-data" role="form">

                    @else

                        <form class="forms-sample" role="form">

                    @endif 

                    @csrf

                
                        @if($static_page_details->id)

                            <input type="hidden" name="static_page_id" value="{{$static_page_details->id}}">

                        @endif

                        <div class="form-body pt-3">

                            <div class="row">

                                <div class="form-group col-md-4">
                                    <div class="form-group">
                                        <label for="title">{{tr('title')}}<span class="admin-required">*</span> </label>
                                        <input type="text" id="title" name="title" class="form-control" placeholder="Enter {{tr('title')}}" required  value="{{old('title')?: $static_page_details->title}}" onkeydown="return alphaOnly(event);">
                                    </div>
                                </div>

                                <div class="form-group col-md-4">

                                    <label for="page">
                                        {{tr('select_section_type')}}

                                        <span class="required" aria-required="true"> <span class="admin-required">*</span> </span>
                                    </label>
                                    
                                    <select class="form-control select2" name="section_type" required>
                                        <option value="">{{tr('select_section_type')}}</option>

                                        @foreach($section_types as $key => $value)

                                            <option value="{{$key}}" @if($key == $static_page_details->section_type) selected @endif>{{ $value }}</option>

                                        @endforeach 
                                    </select>
                                    
                                </div>

                                <div class="form-group col-md-4">

                                    <label for="page">
                                        {{tr('select_static_page_type')}}
                                        <span class="required" aria-required="true"> <span class="admin-required">*</span> </span>
                                    </label>
                                    
                                    <select class="form-control select2" name="type" required>
                                        <option value="">{{tr('select_static_page_type')}}</option>

                                        @foreach($static_keys as $value)

                                            <option value="{{$value}}" @if($value == $static_page_details->type) selected="true" @endif>{{ $value }}</option>

                                        @endforeach 
                                    </select>
                                    
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-12"> 

                                    <div class="form-group">

                                        <label for="description">{{tr('description')}}<span class="admin-required">*</span></label>

                                        <textarea id="ckeditor" rows="5" class="form-control" name="description" placeholder="{{ tr('description') }}">{{old('description') ?: $static_page_details->description}}</textarea>

                                    </div>

                                </div>

                            </div>

                        </div>

                        <button type="reset" class="btn btn-warning">{{ tr('reset')}}</button>

                        @if(Setting::get('is_demo_control_enabled') == NO )

                            <button type="submit" class="btn btn-success mr-2">{{ tr('submit') }} </button>

                        @else

                            <button type="button" class="btn btn-success mr-2" disabled>{{ tr('submit') }}</button>
                            
                        @endif

                    </form>
                </div>

            </div>

        </div>

    </div>
    
</div>

resources/views/admin/static_pages/create.blade.php
@extends('layouts.admin')

@section('title', tr('add_static_page'))

@section('content-header', tr('static_pages'))

@section('bread-crumb')

    <li class="breadcrumb-item">
    	<a href="{{ route('admin.static_pages.index') }}">{{tr('static_pages')}}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{tr('add_static_page')}}</span>
    </li>
           
@endsection 

@section('content')
    
    @include('admin.static_pages._form')

@endsection

@section('scripts')

<script src="https://cdn.ckeditor.com/ckeditor5/11.1.1/classic/ckeditor.js"></script>

<script>
    ClassicEditor
        .create( document.querySelector( '#ckeditor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>

@endsection

resources/views/admin/static_pages/edit.blade.php
@extends('layouts.admin')

@section('content-header',tr('static_pages'))

@section('title', tr('edit_static_page'))

@section('bread-crumb')

    <li class="breadcrumb-item"><a href="{{ route('admin.static_pages.index') }}">{{tr('static_pages')}}</a></li>

    <li class="breadcrumb-item active" aria-current="page">
        <span>{{ tr('edit_static_page') }}</span>
    </li>
           
@endsection 

@section('content')

    @include('admin.static_pages._form')

@endsection

@section('scripts')

<script src="https://cdn.ckeditor.com/ckeditor5/11.1.1/classic/ckeditor.js"></script>

<script>
    ClassicEditor
        .create( document.querySelector( '#ckeditor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>

@endsection

resources/views/admin/static_pages/index.blade.php
@extends('layouts.admin') 

@section('content-header',tr('static_pages'))

@section('title', tr('view_static_pages'))

@section('bread-crumb')

    <li class="breadcrumb-item"><a href="{{ route('admin.static_pages.index' )}}">{{tr('static_pages')}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">
        <span>{{ tr('view_static_pages') }}</span>
    </li>
           
@endsection 

@section('content')

<div class="col-lg-12 grid-margin stretch-card">
        
    <div class="card">

        <div class="card-body">

            <div class="border-bottom pb-3">

                <h5 class="text-uppercase">{{tr('view_static_pages')}}

                    <a class="btn btn-outline-primary float-right" href="{{route('admin.static_pages.create')}}">
                        <i class="fa fa-plus"></i> {{tr('add_static_page')}}
                    </a>
              
                </h5>

            </div>

            <div class="table-responsive pb-3 pt-3">

                <table id="basic-datatable" class="table dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>{{tr('s_no')}}</th>
                            <th>{{tr('title')}}</th>
                            <th>{{tr('static_page_type')}}</th>
                            <th>{{tr('section_type')}}</th>
                            <th>{{tr('status')}}</th>
                            <th>{{tr('action')}}</th>
                        </tr>
                    </thead>

                    <tbody>


                        @foreach($static_pages as $i => $static_page_details)

                            <tr>
                                <td>{{$i+$static_pages->firstItem()}}</td>

                                <td>
                                    <a href="{{route('admin.static_pages.view' , ['static_page_id'=> $static_page_details->id] )}}"> {{$static_page_details->title}}</a>
                                </td>

                                <td class="text-capitalize">{{$static_page_details->type}}</td>

                                <td>{{static_page_footers($static_page_details->section_type)}}</td>

                                <td>
                                    @if($static_page_details->status == APPROVED)

                                      <span class="badge badge-success">{{tr('approved')}}</span> 

                                    @else

                                      <span class="badge badge-warning">{{tr('pending')}}</span> 
                                    @endif
                                </td>

                                <td>   
                                    <div class="dropdown">

                                         <button class="btn btn-outline-primary  dropdown-toggle" type="button" id="dropdownMenuOutlineButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                {{tr('action')}}
                                        </button>

                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuOutlineButton1">

                                            <a class="dropdown-item" href="{{ route('admin.static_pages.view', ['static_page_id' => $static_page_details->id] ) }}">
                                                {{tr('view')}}
                                            </a>

                                            @if(Setting::get('is_demo_control_enabled') == NO)
                                            
                                                <a class="dropdown-item" href="{{ route('admin.static_pages.edit', ['static_page_id' => $static_page_details->id] ) }}">
                                                    {{tr('edit')}}
                                                </a>

                                                <a class="dropdown-item" 
                                                onclick="return confirm(&quot;{{tr('static_page_delete_confirmation' , $static_page_details->title)}}&quot;);" href="{{ route('admin.static_pages.delete', ['static_page_id' => $static_page_details->id] ) }}" >
                                                    {{ tr('delete') }}
                                                </a>

                                            @else

                                                <a class="dropdown-item text-muted" href="javascript:;">{{tr('edit')}}</a>

                                                <a class="dropdown-item text-muted" href="javascript:;">{{ tr('delete') }}</a>

                                            @endif                                               

                                            <div class="dropdown-divider"></div>

                                            <div class="dropdown-divider"></div>

                                            @if($static_page_details->status == APPROVED)

                                                <a class="dropdown-item" href="{{ route('admin.static_pages.status', ['static_page_id' =>  $static_page_details->id] ) }}" 
                                                onclick="return confirm(&quot;{{$static_page_details->title}} - {{tr('static_page_decline_confirmation')}}&quot;);"> 
                                                    {{tr('decline')}}
                                                </a>

                                            @else

                                                <a class="dropdown-item" href="{{ route('admin.static_pages.status', ['static_page_id' =>  $static_page_details->id] ) }}">
                                                    {{tr('approve')}}
                                                </a>
                                                   
                                            @endif

                                        </div>
                                         
                                    </div>
                                

                                </td>
                            
                            </tr>

                        @endforeach

                    </tbody>

                </table>

                <div class="float-right">{{$static_pages->links()}}</div>

            </div>

        </div>
    
    </div>

</div>

@endsection

resources/views/admin/static_pages/view.blade.php
@extends('layouts.admin') 

@section('content-header',tr('static_pages'))

@section('title', tr('view_static_page'))

@section('bread-crumb')

    <li class="breadcrumb-item"><a href="{{route('admin.static_pages.index')}}">{{tr('static_pages')}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">
        <span>{{tr('view_static_page')}}</span>
    </li>
           
@endsection  

@section('content')

<div class="col-lg-12 grid-margin stretch-card">
        
    <div class="card">

        <div class="card-body">

            <div class="border-bottom pb-3">

                <h5 class="text-uppercase">{{tr('view_static_pages')}}
              
                </h5>

            </div>

            <div class="card-group">

                <!-- Card -->
                <div class="card mb-4">

                    <!-- Card content -->
                    <div class="card-body">

                        <!-- Title -->
                        <h4 class="card-title">{{ tr('description') }}</h4>
                        <!-- Text -->
                        <p class="card-text"><?= $static_page_details->description ?></p>
                        
                    </div>
                    <!-- Card content -->

                </div>
                <!-- Card -->

                <!-- Card -->
                <div class="card mb-4">

                    <!-- Card content -->
                    <div class="card-body">

                        <div class="custom-card">
                        
                            <h5 class="card-title">{{tr('title')}}</h5>
                            
                            <p class="card-text">{{$static_page_details->title}}</p>

                        </div> 

                        <div class="custom-card">
                        
                            <h5 class="card-title">{{tr('static_page_type')}}</h5>
                            
                            <p class="card-text">{{$static_page_details->title}}</p>

                        </div>

                        <div class="custom-card">
                        
                            <h5 class="card-title">{{tr('section_type')}}</h5>
                            
                            <p class="card-text">{{static_page_footers($static_page_details->section_type, $is_list = NO)}}</p>

                        </div> 

                        <div class="custom-card">
                        
                            <h5 class="card-title">{{tr('status')}}</h5>
                            
                            <p class="card-text">

                                @if($static_page_details->status == APPROVED)

                                    <span class="badge badge-success badge-md text-uppercase">{{tr('approved')}}</span>

                                @else 

                                    <span class="badge badge-danger badge-md text-uppercase">{{tr('pending')}}</span>

                                @endif
                            
                            </p>

                        </div>
                                                
                        <div class="custom-card">
                        
                            <h5 class="card-title">{{tr('updated_at')}}</h5>
                            
                            <p class="card-text">{{ common_date($static_page_details->updated_at,Auth::guard('admin')->user()->timezone) }}</p>

                        </div>

                        <div class="custom-card">
                        
                            <h5 class="card-title">{{tr('created_at')}}</h5>
                            
                            <p class="card-text">{{ common_date($static_page_details->created_at,Auth::guard('admin')->user()->timezone) }}</p>

                        </div> 

                        <div class="custom-card">
                            <div class="row">
                                
                            
                            @if(Setting::get('is_demo_control_enabled') == NO)
                                <div class="col-md-4 col-lg-4">

                                    <a href="{{ route('admin.static_pages.edit', ['static_page_id'=> $static_page_details->id] ) }}" class="btn btn-primary btn-block">{{tr('edit')}}</a>
                                    
                                </div>                              

                                <div class="col-md-4 col-lg-4">
                                    <a onclick="return confirm(&quot;{{tr('static_page_delete_confirmation' , $static_page_details->title)}}&quot;);" href="{{ route('admin.static_pages.delete', ['static_page_id'=> $static_page_details->id] ) }}" class="btn btn-danger btn-block">
                                        {{ tr('delete') }}
                                    </a>

                                </div>                               

                            @else
                            
                                <div class="col-md-4 col-lg-4">
                                    
                                    <button class="btn btn-primary btn-block" disabled>{{ tr('edit') }}</button>

                                </div>
                                
                                <div class="col-md-4 col-lg-4">
                                    
                                    <button class="btn btn-warning btn-block" disabled>{{ tr('delete') }}</button>
                                </div>
                                

                            @endif

                            @if($static_page_details->status == APPROVED)

                                <div class="col-md-4 col-lg-4">
                                    
                                    <a class="btn btn-warning btn-block" href="{{ route('admin.static_pages.status', ['static_page_id'=> $static_page_details->id] ) }}" onclick="return confirm(&quot;{{ $static_page_details->title }}-{{tr('static_page_decline_confirmation' , $static_page_details->title)}}&quot;);">

                                        {{tr('decline')}}
                                    </a>
                                </div>

                            @else

                                <div class="col-md-4 col-lg-4">
                                     <a class="btn btn-success btn-block" href="{{ route('admin.static_pages.status', ['static_page_id'=> $static_page_details->id] ) }}">
                                        {{tr('approve')}}
                                    </a>
                                </div>
                                   
                            @endif

                            </div>

                        </div>

                    </div>
                    <!-- Card content -->

                </div>

                <!-- Card -->

            </div>


        </div>
    
    </div>

</div>


@endsection