routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('users/subscriptions','AdminController@users_subscriptions_index')->name('users.subscriptions_index');

        Route::post('users/subscription_payments','AdminController@users_subscription_payments_save')->name('users.subscriptions_payments');

        Route::get('users/subscriptions_payments/delete','AdminController@users_subscription_payments_delete')->name('users.subscriptions_payments_delete');

        //subscriptions
        Route::get('subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'AdminController@subscriptions_status')->name('subscriptions.status');

        //Subscription Payments
        Route::get('subscription_payments/index','AdminController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','AdminController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenue/dashboard','AdminController@revenue_dashboard')->name('revenue.dashboard');

        //meetings crud
        Route::get('meetings', 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/create', 'AdminController@meetings_create')->name('meetings.create');

        Route::get('meetings/edit', 'AdminController@meetings_edit')->name('meetings.edit');

        Route::post('meetings/save', 'AdminController@meetings_save')->name('meetings.save');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');

        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');

        Route::get('meetings/status', 'AdminController@meetings_status')->name('meetings.status');

        // settings

        Route::get('settings-control', 'AdminController@settings_control')->name('control');

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 
        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('/static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('/static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('/static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('/static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('/static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('/static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('/static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        // SUPPORT CONTACTS

        Route::get('support_contacts' , 'AdminController@support_contacts_index')->name('support_contacts.index');

        Route::get('support_contacts/view', 'AdminController@support_contacts_view')->name('support_contacts.view');


        Route::get('meeting_records', 'AdminController@meeting_records_index')->name('meeting_records.index');

        Route::get('meeting_records/view', 'AdminController@meeting_records_view')->name('meeting_records.view');

        Route::get('meeting_records/delete', 'AdminController@meeting_records_delete')->name('meeting_records.delete');

    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Setting, DB;
use App\Notifications\ResetPassword as ResetPasswordNotification;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $appends = [
        'user_id', 'user_unique_id'
    ];

    public function getUserIdAttribute() {

        return $this->id;
    }

    public function getUserUniqueIdAttribute() {

        return $this->unique_id;
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the UserCard record associated with the user.
     */
    public function userCards() {
        
        return $this->hasMany(UserCard::class, 'user_id');
    }

    public function getSubscribedusers()
    {
        return $this->hasMany(SubscriptionPayment::class, 'user_id', 'id');
    }

    public function getMeetingUsers() {

        return $this->hasMany(MeetingUser::class, 'user_id');
    }

    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

            $model->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            if (Setting::get('is_account_email_verification') == YES && envfile('MAIL_USERNAME') && envfile('MAIL_PASSWORD')) { 

                if($model->attributes['login_by'] == 'manual') {

                    $model->generateEmailCode();

                }

            }

            $model->attributes['payment_mode'] = COD;

            $model->attributes['username'] = routefreestring($model->attributes['name']).rand(1,999999);

            $model->attributes['unique_id'] = uniqid();

            $model->attributes['token'] = \Helper::generate_token();

            $model->attributes['token_expiry'] = \Helper::generate_token_expiry();

            $model->attributes['status'] = USER_APPROVED;

            if(in_array($model->attributes['login_by'], ['facebook', 'google', 'apple', 'linkedin', 'instagram'] )) {
                
                $model->attributes['password'] = \Hash::make($model->attributes['social_unique_id']);
            }

        });

        static::created(function($model) {

            $model->attributes['email_notification_status'] = $model->attributes['push_notification_status'] = YES;

            $model->attributes['unique_id'] = "UID"."-".$model->attributes['id']."-".uniqid();

            $model->save();
        
        });

        static::updating(function($model) {

            $model->attributes['username'] = routefreestring($model->attributes['name']).rand(1,999999);

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

        });

        static::deleting(function ($model){

            \Helper::delete_file($model->picture , PROFILE_PATH_USER);

            $model->userCards()->delete();

            $model->Meeting()->delete();

            $model->SubscriptionPayment()->delete();

            $model->SupportContact()->delete();

            $model->meetingUsers()->delete();

        });

    }


    /**
     * Get the meetings record associated with the user.
     */
    public function Meeting() {
        
        return $this->hasMany(Meeting::class, 'user_id');
    }

    public function SubscriptionPayment() {
        
        return $this->hasMany(SubscriptionPayment::class, 'user_id');
    }

    public function SupportContact() {
        
        return $this->hasMany(SupportContact::class, 'user_id');
    }

    public function meetingUsers() {

        return $this->hasMany(MeetingUser::class,'user_id');
    }

    /**
     * Generates Token and Token Expiry
     * 
     * @return bool returns true if successful. false on failure.
     */

    protected function generateEmailCode() {

        $this->attributes['verification_code'] = \Helper::generate_email_code();

        $this->attributes['verification_code_expiry'] = \Helper::generate_email_expiry();

        // Check Email verification controls and email configurations

        if(Setting::get('is_account_email_verification') == YES && Setting::get('is_email_notification') == YES && Setting::get('is_email_configured') == YES) {

            if($model->attributes['login_by'] != 'manual') {

                $this->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            } else {

                $this->attributes['is_verified'] = USER_EMAIL_NOT_VERIFIED;
            }

        } else { 

            $this->attributes['is_verified'] = USER_EMAIL_VERIFIED;
        }

        return true;
    
    }

}

resources/views/admin/users/_search.blade.php
 <form  action="{{route('admin.users.index')}}" method="GET" role="search">

    <div class="row pt-2 pb-2">

        <div class="col-3">
            @if(Request::has('search_key'))
                <p class="text-muted">Search results for <b>{{Request::get('search_key')}}</b></p>
            @endif
        </div>
        
        <div class="col-3">

            <select class="form-control select2" name="status">

                <option  class="select-color" value="">{{tr('select_status')}}</option>

                <option  class="select-color" value="{{SORT_BY_APPROVED}}">{{tr('approved')}}</option>

                <option  class="select-color" value="{{SORT_BY_DECLINED}}">{{tr('declined')}}</option>

                <option  class="select-color" value="{{SORT_BY_EMAIL_VERIFIED}}">{{tr('verified')}}</option>

                <option  class="select-color" value="{{SORT_BY_EMAIL_NOT_VERIFIED}}">{{tr('un_verified')}}</option>

            </select>

        </div>

        <div class="col-6">

            <div class="input-group">
                <input type="text" class="form-control" name="search_key"
                    placeholder="{{tr('users_search_placeholder')}}"> <span class="input-group-btn">
                    &nbsp

                    <button type="submit" class="btn btn-primary btn-width">
                       {{tr('search')}}
                    </button>

                    <a class="btn btn-primary" href="{{route('admin.users.index')}}">{{tr('clear')}}
                    </a>
                </span>
            </div>

        </div>

    </div>

</form>

resources/views/admin/users/create.blade.php
@extends('layouts.admin') 

@section('content-header', tr('users'))

@section('bread-crumb')

    <li class="breadcrumb-item">
    	<a href="{{ route('admin.users.index') }}">{{tr('users')}}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{tr('add_user')}}</span>
    </li>
           
@endsection 

@section('content') 

	@include('admin.users._form') 

@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content-header', tr('users'))

@section('bread-crumb')

    <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">{{tr('users')}}</a></li>
    
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{ tr('edit_user') }}</span>
    </li>
           
@endsection 

@section('content')

	@include('admin.users._form')

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin') 

@section('content-header', tr('users'))

@section('bread-crumb')

    <li class="breadcrumb-item"><a href="{{ route('admin.users.index')}}">{{tr('users')}}</a></li>

    <li class="breadcrumb-item active" aria-current="page">
        <span>{{ tr('view_users') }}</span>
    </li> 
           
@endsection 

@section('content')

<div class="row">

    <div class="col-12">

        <div class="card">

            <div class="card-body">

                <div class="border-bottom pb-3">

                    <h5 class="text-uppercase">{{tr('view_users')}}

                        <a class="btn btn-outline-primary float-right user_add" href="{{route('admin.users.create')}}">
                            <i class="fa fa-plus"></i> {{tr('add_user')}}
                        </a>
                  
                    </h5>

                </div>

                @include('admin.users._search')
                
                <table id="basic-datatable" class="table dt-responsive nowrap">

                    <thead>
                        <tr>
                            <th>{{tr('s_no')}}</th>
                            <th>{{tr('name')}}</th>
                            <th>{{tr('email')}}</th>
                            <th>{{tr('mobile')}}</th>   
                            <th>{{tr('status')}}</th>
                            <th>{{tr('verify')}}</th>
                            <th>{{tr('action')}}</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($users as $i => $user_details)
                              
                            <tr>
                                <td>{{$i+$users->firstItem()}}</td>

                                <td>
                                    <a href="{{route('admin.users.view' , ['user_id' => $user_details->id])}}"> {{ $user_details->name }}
                                    </a>
                                </td>

                                <td> {{ $user_details->email }} </td>

                                <td> {{ ($user_details->mobile > 1) ? $user_details->mobile : tr('unavailable')}} </td>

                                <td>

                                    @if($user_details->status == USER_APPROVED)

                                        <span class="badge badge-success">{{ tr('approved') }} </span>

                                    @else

                                        <span class="badge badge-danger">{{ tr('declined') }} </span>

                                    @endif

                                </td>

                                <td>   

                                    @if($user_details->is_verified == USER_EMAIL_VERIFIED) 

                                        <span class="badge badge-success">{{ tr('verified') }} </span>

                                    @else

                                        <a class="badge badge-info" href="{{ route('admin.users.verify', ['user_id' => $user_details->id]) }}"> 
                                            {{ tr('verify') }} 
                                        </a>

                                    @endif  
                                                                  
                                </td>

                                <td>     

                                    <div class="template-demo">

                                        <div class="dropdown">

                                            <button class="btn btn-outline-primary  dropdown-toggle" type="button" id="dropdownMenuOutlineButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                {{tr('action')}}
                                            </button>

                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuOutlineButton1">
                                              
                                                <a class="dropdown-item" href="{{ route('admin.users.view', ['user_id' => $user_details->id]) }}">
                                                    {{tr('view')}}
                                                </a>
                                                
                                                @if(Setting::get('is_demo_control_enabled') == NO)
                                                    <a class="dropdown-item" href="{{ route('admin.users.edit', ['user_id' => $user_details->id]) }}">
                                                        {{tr('edit')}}
                                                    </a>
                                                    
                                                    <a class="dropdown-item" href="{{route('admin.users.delete', ['user_id' => $user_details->id])}}" 
                                                    onclick="return confirm(&quot;{{tr('user_delete_confirmation' , $user_details->name)}}&quot;);">
                                                        {{tr('delete')}}
                                                    </a>
                                                @else

                                                    <a class="dropdown-item text-muted" href="javascript:;">{{tr('edit')}}</a>
                                                  
                                                    <a class="dropdown-item text-muted" href="javascript:;">{{tr('delete')}}</a>                           
                                                @endif

                                                <div class="dropdown-divider"></div>

                                                @if($user_details->is_verified == USER_EMAIL_NOT_VERIFIED) 

                                                    <a class="dropdown-item" href="{{ route('admin.users.verify', ['user_id' => $user_details->id]) }}"> {{ tr('verify') }} 
                                                    </a>

                                                @endif 

                                                @if($user_details->status == USER_APPROVED)

                                                    <a class="dropdown-item" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}" onclick="return confirm(&quot;{{$user_details->first_name}} - {{tr('user_decline_confirmation')}}&quot;);" >
                                                        {{ tr('decline') }} 
                                                    </a>

                                                @else
                                                    
                                                    <a class="dropdown-item" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}">
                                                        {{ tr('approve') }} 
                                                    </a>
                                                       
                                                @endif

                                                @if($user_details->is_verified == USER_EMAIL_VERIFIED)

                                                <a class="dropdown-item" href="{{ route('admin.users.verify',['user_id' => $user_details->id] ) }}">
                                                    {{ tr('unverify') }}
                                                </a>
                                                @else

                                                <a class="dropdown-item" href="{{ route('admin.users.verify',['user_id' => $user_details->id] ) }}">
                                                    {{ tr('verify') }}
                                                </a>

                                                @endif

                                                <a class="dropdown-item" href="{{route('admin.users.subscriptions_index',['user_id' => $user_details->id])}}">{{tr('subscriptions')}}</a>

                                                <a class="dropdown-item" href="{{route('admin.meetings.index',['user_id' => $user_details->id])}}">{{tr('view_meetings')}}</a>

                                            </div>

                                        </div>

                                    </div>

                                </td>

                            </tr>

                        @endforeach
                    </tbody>
                   
                </table>

                <div class="float-right" id="paglink">{{ $users->appends(request()->input())->links() }}</div>

            </div>
            
        </div>
       
    </div>
   
</div>




@endsection

resources/views/admin/users/view.blade.php
@extends('layouts.admin')

@section('content-header', tr('users'))

@section('bread-crumb')

<li class="breadcrumb-item"><a href="{{ route('admin.users.index')}}">{{tr('users')}}</a></li>

<li class="breadcrumb-item active" aria-current="page">
	<span>{{ tr('view_users') }}</span>
</li>

@endsection

@section('content')

<div class="row">

	<div class="col-12">

		<div class="card card-navy card-outline">

			<div class="card-body">

				<div class="row">

					<div class="col">

						<div class="card">

							<div class="card-body p-0">

								<h4 class="card-title border-bottom p-3 mb-0 header-title text-uppercase">{{tr('view_users')}}</h4>

								<div class="row py-1">

									<div class="col-xl-3 col-sm-6">

										<div class="media p-3">

											<i data-feather="grid" class="align-self-center icon-dual icon-lg mr-4"></i>

											<div class="media-body">
												<h4 class="mt-0 mb-0">{{$user_details->total_meetings}}</h4>
												<span class="text-muted font-size-13">{{tr('total_meetings')}}</span>
											</div>

										</div>

									</div>

									<div class="col-xl-3 col-sm-6">

										<div class="media p-3">

											<i data-feather="check-square" class="align-self-center icon-dual icon-lg mr-4"></i>

											<div class="media-body">
												<h4 class="mt-0 mb-0">{{$user_details->today_meetings}}</h4>
												<span class="text-muted">{{tr('today_meetings')}}</span>
											</div>

										</div>

									</div>

									<div class="col-xl-3 col-sm-6">

										<div class="media p-3">

											<i data-feather="clock" class="align-self-center icon-dual icon-lg mr-4"></i>

											<div class="media-body">
												<h4 class="mt-0 mb-0">{{$user_details->upcoming_meetings}}</h4>
												<span class="text-muted">{{tr('upcoming_meetings')}}</span>
											</div>

										</div>

									</div>

									<div class="col-xl-3 col-sm-6">

										<div class="media p-3">

											<i data-feather="trash" class="align-self-center icon-dual icon-lg mr-4"></i>
											<div class="media-body">
												<h4 class="mt-0 mb-0">{{$user_details->cancelled_meetings}}</h4>
												<span class="text-muted">{{tr('cancelled_meetings')}}</span>
											</div>

										</div>

									</div>

								</div>

							</div>

						</div>

					</div>

				</div>

				<div class="row">

					<div class="col-md-6">

						<div class="card card-widget widget-user-2">

							<div class="widget-user-header pb-3">
								<div class="widget-user-image">
									<img class="user-image" src="{{$user_details->picture ?: asset('placeholder.jpeg')}}" alt="User Avatar" />
								</div>
							</div>

							<h6 class="card-title border-bottom p-3 mb-0 header-title">{{tr('action')}}</h6>

							@if(Setting::get('is_demo_control_enabled') == NO)

							<div class="row pt-3">

								<div class="col-md-3 col-lg-3 action_button">
									<a class="btn btn-success width-md" href="{{ route('admin.users.edit', ['user_id' => $user_details->id]) }}">
										{{tr('edit')}}
									</a>
								</div>

								<div class="col-md-3 col-lg-3 action_button">
									<a class="btn btn-danger width-md" href="{{route('admin.users.delete', ['user_id' => $user_details->id])}}" onclick="return confirm(&quot;{{tr('user_delete_confirmation' , $user_details->name)}}&quot;);">
										{{tr('delete')}}
									</a>
								</div>

							</div>

							@else
							<div class="row">

								<div class="col-md-3">
									<a class="btn btn-success width-md" href="user_details:;">{{tr('edit')}}</a>
								</div>

								<div class="col-md-3">
									<a class="btn btn-delete width-md" href="javascript:;" onclick="return confirm(&quot;{{tr('user_delete_confirmation' , $user_details->name)}}&quot;);">{{tr('delete')}}</a>
								</div>

							</div>

							@endif

							<div class="row pt-3">

								<div class="col-md-3">

									@if($user_details->status == APPROVED)

									<a class="btn btn-danger width-md" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}" onclick="return confirm(&quot;{{$user_details->name}} - {{tr('user_decline_confirmation')}}&quot;);">
										{{ tr('decline') }}
									</a>

									@else

									<a class="btn btn-success width-md" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}">
										{{ tr('approve') }}
									</a>

									@endif
								</div>

								<div class="col-md-3">
									@if($user_details->is_verified == USER_EMAIL_NOT_VERIFIED)

									<a class="btn btn-info width-md" href="{{ route('admin.users.verify', ['user_id' => $user_details->id]) }}"> {{ tr('verify') }}
									</a>

									@endif
								</div>

							</div>

							<div class="row pt-3">

							    <div class="col-md-3">
									
									<a class="btn btn-info width-md" href="{{ route('admin.meetings.index', ['user_id' => $user_details->id]) }}"> {{ tr('meetings') }}
									</a>

								</div>
							
							</div>

							<br>

						</div>

					</div>

					<div class="col-md-6">

						<div class="card card-widget widget-user-2">

							<div class="card-body p-0">

								<ul class="nav flex-column">

									<li class="nav-item">
										<div href="#" class="nav-link">{{tr('name')}} <span class="float-right text-uppercase">{{$user_details->name}}</span> </div>
									</li>

									<li class="nav-item">
										<div href="#" class="nav-link">{{tr('email')}}<span class="float-right text-uppercase">{{$user_details->email}}</span> </div>
									</li>

									<li class="nav-item">
										<div class="nav-link">{{tr('mobile')}}<span class="float-right text-uppercase">{{$user_details->mobile ?: tr('unavailable')}}</span> </div>
									</li>

									<li class="nav-item">
										<div class="nav-link"> {{tr('payment_mode')}} <span class="float-right badge badge-secondary text-uppercase">{{$user_details->payment_mode}}</span></div>
									</li>

									<li class="nav-item">
										<div class="nav-link">{{tr('is_verified')}}
											@if($user_details->is_verified == USER_EMAIL_VERIFIED)
											<span class="float-right badge badge-primary text-uppercase">{{tr('yes')}}</span>
											@else
											<span class="float-right badge badge-danger text-uppercase">{{tr('no')}}</span>
											@endif
										</div>
									</li>

									<li class="nav-item">
										<div class="nav-link">{{tr('status')}}
											@if($user_details->status == APPROVED)
											<span class="float-right badge badge-success text-uppercase">{{tr('approved')}}</span>
											@else
											<span class="float-right badge badge-danger text-uppercase">{{tr('declined')}}</span>
											@endif
										</div>
									</li>
									
									<li class="nav-item">
										<div href="#" class="nav-link">{{tr('device_type')}} <span class="float-right badge badge-info text-uppercase">{{$user_details->device_type}}</span> </div>
									</li>

									<li class="nav-item">
										<div class="nav-link">{{tr('login_by')}}<span class="float-right text-uppercase">{{$user_details->login_by}}</span></div>
									</li>


									<li class="nav-item">
										<div class="nav-link">{{tr('created_at')}}<span class="float-right">{{common_date($user_details->created_at,Auth::guard('admin')->user()->timezone)}}</span></div>
									</li>

									<li class="nav-item">
										<div class="nav-link">{{tr('updated_at')}}<span class="float-right">{{common_date($user_details->updated_at,Auth::guard('admin')->user()->timezone)}}</span></div>
									</li>

								</ul>

							</div>

						</div>

					</div>

					

				</div>

			</div>

		</div>

	</div>

</div>

@endsection