routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('users/subscriptions','AdminController@users_subscriptions_index')->name('users.subscriptions_index');

        Route::post('users/subscription_payments','AdminController@users_subscription_payments_save')->name('users.subscriptions_payments');

        Route::get('users/subscriptions_payments/delete','AdminController@users_subscription_payments_delete')->name('users.subscriptions_payments_delete');

        //subscriptions
        Route::get('subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'AdminController@subscriptions_status')->name('subscriptions.status');

        //Subscription Payments
        Route::get('subscription_payments/index','AdminController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','AdminController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenue/dashboard','AdminController@revenue_dashboard')->name('revenue.dashboard');

        //meetings crud
        Route::get('meetings', 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/create', 'AdminController@meetings_create')->name('meetings.create');

        Route::get('meetings/edit', 'AdminController@meetings_edit')->name('meetings.edit');

        Route::post('meetings/save', 'AdminController@meetings_save')->name('meetings.save');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');

        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');

        Route::get('meetings/status', 'AdminController@meetings_status')->name('meetings.status');

        // settings

        Route::get('settings-control', 'AdminController@settings_control')->name('control');

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 
        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('/static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('/static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('/static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('/static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('/static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('/static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('/static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        // SUPPORT CONTACTS

        Route::get('support_contacts' , 'AdminController@support_contacts_index')->name('support_contacts.index');

        Route::get('support_contacts/view', 'AdminController@support_contacts_view')->name('support_contacts.view');


        Route::get('meeting_records', 'AdminController@meeting_records_index')->name('meeting_records.index');

        Route::get('meeting_records/view', 'AdminController@meeting_records_view')->name('meeting_records.view');

        Route::get('meeting_records/delete', 'AdminController@meeting_records_delete')->name('meeting_records.delete');

    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

resources/views/layouts/admin/_logout_model.blade.php
<div class="modal fade" id="logoutModel" tabindex="-1" role="dialog" aria-labelledby="logoutModel" aria-hidden="true">

    <div class="modal-dialog modal-dialog-centered" role="document">

        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="logoutModelTitle">{{tr('confirm_logout')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <div class="modal-body">
                <h5>{{tr('logout_note')}}</h5>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-pill" data-dismiss="modal">{{tr('close')}}</button>
                <a class="btn btn-primary btn-pill" href="{{route('admin.logout')}}">{{tr('logout')}}</a>
            </div>

        </div>

    </div>
    
</div>

resources/views/layouts/admin/footer.blade.php
 <!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
               Copyright &copy; {{date('Y')}} {{Setting::get('site_name' , 'CG-school')}}. {{tr('all_right_reserved')}}. 
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->

resources/views/layouts/admin/header.blade.php
<div class="navbar navbar-expand flex-column flex-md-row navbar-custom">
    <div class="container-fluid">
        <!-- LOGO -->
        <a href="{{route('admin.dashboard')}}" class="navbar-brand mr-0 mr-md-2 logo">
            <span class="logo-lg">
                <img src="{{Setting::get('site_icon')}}" alt="" height="24" />
                <span class="d-inline h5 ml-1 text-logo">{{Setting::get('site_name')}}</span>
            </span>
            <span class="logo-sm">
                <img src="{{Setting::get('site_icon')}}" alt="" height="24">
            </span>
        </a>

        <ul class="navbar-nav bd-navbar-nav flex-row list-unstyled menu-left mb-0">
            <li class="">
                <button class="button-menu-mobile open-left disable-btn">
                    <i data-feather="menu" class="menu-icon"></i>
                    <i data-feather="x" class="close-icon"></i>
                </button>
            </li>
        </ul>

        <ul class="navbar-nav flex-row ml-auto d-flex list-unstyled topnav-menu float-right mb-0">

            <li class="dropdown align-self-center">
                <a class="nav-link dropdown-toggle nav-user mr-0" data-toggle="dropdown" href="#" role="button"
                    aria-haspopup="false" aria-expanded="false">
                    <div class="media user-profile ">
                        <img src="{{Auth::guard('admin')->user()->picture}}" alt="user-image" class="rounded-circle align-self-center" />
                        <div class="media-body text-left">
                            <h6 class="pro-user-name ml-2 my-0">
                                <span>{{Auth::guard('admin')->user()->name}}</span>
                                <span class="pro-user-desc text-muted d-block mt-1">Administrator </span>
                            </h6>
                        </div>
                        <span data-feather="chevron-down" class="ml-2 align-self-center"></span>
                    </div>
                </a>
                <div class="dropdown-menu profile-dropdown-items dropdown-menu-right">
                    <a href="{{route('admin.profile')}}" class="dropdown-item notify-item">
                        <i data-feather="user" class="icon-dual icon-xs mr-2"></i>
                        <span>{{tr('my_account')}}</span>
                    </a>

                    <a href="{{route('admin.settings')}}" class="dropdown-item notify-item">
                        <i data-feather="settings" class="icon-dual icon-xs mr-2"></i>
                        <span>{{tr('settings')}}</span>
                    </a>

                    <div class="dropdown-divider"></div>

                     <a class="dropdown-item notify-item" data-toggle="modal" data-target="#logoutModel">
                        <i data-feather="log-out" class="icon-dual icon-xs mr-2"></i>
                        <span>{{tr('logout')}}</span>
                    </a>

                </div>
            </li>
        </ul>
    
    </div>

</div>

resources/views/layouts/admin/right-sidebar.blade.php
 <!-- Right Sidebar -->
<div class="right-bar">
    <div class="rightbar-title">
        <a href="javascript:void(0);" class="right-bar-toggle float-right">
            <i data-feather="x-circle"></i>
        </a>
        <h5 class="m-0">Customization</h5>
    </div>

    <div class="slimscroll-menu">

        <h5 class="font-size-16 pl-3 mt-4">Choose Variation</h5>
        <div class="p-3">
            <h6>Default</h6>
            <a href="index-2.html"><img src="../../admin-assets/assets/images/layouts/vertical.jpg" alt="vertical" class="img-thumbnail demo-img" /></a>
        </div>
        <div class="px-3 py-1">
            <h6>Top Nav</h6>
            <a href="layouts-horizontal.html"><img src="../../admin-assets/assets/images/layouts/horizontal.jpg" alt="horizontal" class="img-thumbnail demo-img" /></a>
        </div>
        <div class="px-3 py-1">
            <h6>Dark Side Nav</h6>
            <a href="layouts-dark-sidebar.html"><img src="../../admin-assets/assets/images/layouts/vertical-dark-sidebar.jpg" alt="dark sidenav" class="img-thumbnail demo-img" /></a>
        </div>
        <div class="px-3 py-1">
            <h6>Condensed Side Nav</h6>
            <a href="layouts-dark-sidebar.html"><img src="../../admin-assets/assets/images/layouts/vertical-condensed.jpg" alt="condensed" class="img-thumbnail demo-img" /></a>
        </div>
        <div class="px-3 py-1">
            <h6>Fixed Width (Boxed)</h6>
            <a href="layouts-boxed.html"><img src="../../admin-assets/assets/images/layouts/boxed.jpg" alt="boxed"
                    class="img-thumbnail demo-img" /></a>
        </div>
    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>

resources/views/layouts/admin/scripts.blade.php
<!-- Vendor js -->
<script src="{{asset('admin-assets/assets/js/vendor.min.js')}}"></script>

<!-- App js -->
<script src="{{asset('admin-assets/assets/js/app.min.js')}}"></script>

 <!-- datatable js -->
<script src="{{asset('admin-assets/assets/libs/datatables/jquery.dataTables.min.js')}}"></script>

<script src="{{asset('admin-assets/assets/libs/datatables/dataTables.bootstrap4.min.js')}}"></script>

<script src="{{asset('admin-assets/assets/libs/datatables/dataTables.responsive.min.js')}}"></script>

<script src="{{asset('admin-assets/assets/libs/datatables/responsive.bootstrap4.min.js')}}"></script>

<script src="{{asset('admin-assets/assets/libs/datatables/dataTables.buttons.min.js')}}"></script>

<script src="{{asset('admin-assets/assets/libs/datatables/buttons.bootstrap4.min.js')}}"></script>

<script src="{{asset('admin-assets/assets/libs/datatables/buttons.html5.min.js')}}"></script>

<script src="{{asset('admin-assets/assets/libs/datatables/buttons.flash.min.js')}}"></script>

<script src="{{asset('admin-assets/assets/libs/datatables/buttons.print.min.js')}}"></script>

<script src="{{asset('admin-assets/assets/libs/datatables/dataTables.keyTable.min.js')}}"></script>

<script src="{{asset('admin-assets/assets/libs/datatables/dataTables.select.min.js')}}"></script>

<!-- Datatables init -->
<script src="{{asset('admin-assets/assets/js/pages/datatables.init.js')}}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

<!-- daterangepicker -->

<script src="{{asset('admin-assets/assets/daterangepicker/moment.min.js')}}"></script>

<script src="{{asset('admin-assets/assets/daterangepicker/daterangepicker.js')}}"></script>s


<script type="text/javascript">

    $(document).ready(function(){
   
        setTimeout(function(){

        $('#basic-datatable_filter').hide();

            $('#basic-datatable_filter').hide();

            $('#basic-datatable_info').hide();
            
         },100),

        setTimeout(function(){

        $('#basic-datatable_length').hide();

            $('#basic-datatable_length').hide();
            
         },100),

        setTimeout(function(){
            
        $('#basic-datatable_paginate').hide();

            $('#basic-datatable_paginate').hide();
            
         },100);

     });

</script>

<script type="text/javascript">

    $("#{{$main_page}}").addClass("mm-active");

    @if(isset($sub_page))

        $("#{{$page}}").addClass('mm-show'); 

        var meeting = "{{$sub_page}}";
        
        if(meeting == 'meetings-scheduled') {
            $("#meetings-index").removeClass("active"); 
        }

        $("#{{$sub_page}}").addClass("active"); 

    @endif

    $(document).ready(function() {

        $('.select2').select2();

        $('select').on("select2:close", function () { $(this).focus(); });

        $('.js-example-basic-multiple').select2();

    });

</script>

resources/views/layouts/admin/sidebar.blade.php
 <div class="left-side-menu">

    <div class="media user-profile mt-2 mb-2">
        <img src="{{Auth::guard('admin')->user()->picture}}" class="avatar-sm rounded-circle mr-2" alt="{{Auth::guard('admin')->user()->name}}" />
        <img src="{{Auth::guard('admin')->user()->picture}}" class="avatar-xs rounded-circle mr-2" alt="{{Auth::guard('admin')->user()->name}}" />

        <div class="media-body">
            <h6 class="pro-user-name mt-0 mb-0">{{Auth::guard('admin')->user()->name}}</h6>
            <span class="pro-user-desc">Administrator</span>
        </div>
        
    </div>

    <div class="sidebar-content">

        <div id="sidebar-menu" class="slimscroll-menu">

            <ul class="metismenu" id="menu-bar">

                <li>
                    <a href="{{route('admin.dashboard')}}">
                        <i data-feather="home"></i>
                        <span>{{tr('dashboard')}}</span>
                    </a>
                </li>
               
                <li id="users-crud">

                    <a href="javascript: void(0);">
                        <i data-feather="user"></i>
                        <span>{{tr('users')}}</span>
                        <span class="menu-arrow"></span>
                    </a>

                    <ul class="nav-second-level" aria-expanded="false" id="users">
                        <li>
                            <a href="{{route('admin.users.create')}}" id="users-create">
                                {{tr('add_user')}}
                            </a>
                        </li>
                        <li>
                            <a href="{{route('admin.users.index')}}" id="users-view">
                                {{tr('view_users')}}
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="menu-title">{{tr('meeting_management')}}</li>

                <li id="meetings-crud">

                    <a href="javascript: void(0);">
                        <i data-feather="phone"></i>
                        <span>{{tr('meetings')}}</span>
                        <span class="menu-arrow"></span>
                    </a>
                    
                    <ul class="nav-second-level" aria-expanded="false" id="meetings">

                        <li>
                            <a href="{{route('admin.meetings.index')}}" id="meetings-index">
                                {{tr('meetings_history')}}
                            </a>
                        </li>

                        <li>
                            <a href="{{route('admin.meeting_records.index')}}" id="meetings-records">
                                {{tr('meeting_records')}}
                            </a>
                        </li>

                        <li>
                            <a href="{{route('admin.meetings.index', ['type' => 'scheduled'])}}" id="meetings-scheduled">
                                {{tr('scheduled_meetings')}}
                            </a>
                        </li>

                    </ul>

                </li>
                
                <li class="menu-title">{{tr('revenue_management')}}</li>

                <li id="subscriptions-crud">
                    <a href="javascript: void(0);">
                        <i data-feather="key" class="icon-dual"></i>
                        <span>{{tr('subscriptions')}}</span>
                        <span class="menu-arrow"></span>
                    </a>

                    <ul class="nav-second-level" aria-expanded="false" id="subscriptions">
                        <li>
                            <a href="{{route('admin.subscriptions.create')}}" id="subscriptions-create">
                                {{tr('add_subscription')}}
                            </a>
                        </li>
                        <li>
                            <a href="{{route('admin.subscriptions.index')}}" id="subscriptions-view">
                                {{tr('view_subscriptions')}}
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="payments-crud">
                    <a href="javascript: void(0);">
                        <i data-feather="credit-card" class="icon-dual"></i>
                        <span>{{tr('payments')}}</span>
                        <span class="menu-arrow"></span>
                    </a>

                    <ul class="nav-second-level" aria-expanded="false" id="payments">

                        <li>
                            <a href="{{route('admin.revenue.dashboard')}}"  id="revenues-dashboard">
                                {{tr('revenue_dashboard')}}
                            </a>
                        </li>

                        <li>
                            <a href="{{route('admin.subscription_payments.index')}}" id="subscription-payments">
                                {{tr('subscription_payments')}}
                            </a>
                        </li>

                    </ul>

                </li>

                <li class="menu-title">{{tr('setting_management')}}</li>

                <li id="static_pages-crud">
                    <a href="javascript: void(0);">
                        <i data-feather="file-text" class="icon-dual"></i>
                        <span>{{tr('static_pages')}}</span>
                        <span class="menu-arrow"></span>
                    </a>

                    <ul class="nav-second-level" aria-expanded="false" id="static_pages">

                        <li>
                            <a href="{{route('admin.static_pages.create')}}"  id="static_pages-create">
                                {{tr('add_static_page')}}
                            </a>
                        </li>

                        <li>
                            <a href="{{route('admin.static_pages.index')}}" id="static_pages-view">
                                {{tr('view_static_pages')}}
                            </a>
                        </li>

                    </ul>

                </li>

                <li>
                    <a href="{{route('admin.support_contacts.index')}}" aria-expanded="false">
                        <i data-feather="search"></i>
                        <span>{{tr('support_contacts')}} </span>
                    </a>
                </li>

                <li>
                    <a href="{{route('admin.settings')}}" aria-expanded="false">
                        <i data-feather="settings"></i>
                        <span>{{tr('settings')}} </span>
                    </a>
                </li>

                <li>
                    <a href="{{route('admin.profile')}}" aria-expanded="false">
                        <i data-feather="star"></i>
                        <span> {{tr('profile')}} </span>
                    </a>
                </li>

                <li>
                    <a data-toggle="modal" data-target="#logoutModel" aria-expanded="false">
                        <i data-feather="log-out"></i>
                        <span> {{tr('logout')}} </span>
                    </a>
                </li>
               
            </ul>

        </div>

        <div class="clearfix"></div>

    </div>

</div>